### PR TITLE
Update max tokens and docstring

### PR DESCRIPTION
**Pull request by zmeir**
## PR Type:
Enhancement

___
## PR Description:
This PR includes an update to the maximum tokens for 'gpt-3.5-turbo' and a modification in the docstring. The max tokens for 'gpt-3.5-turbo' has been increased from 4000 to 4001.

___
## PR Main Files Walkthrough:
- `pr_agent/algo/__init__.py`: The maximum tokens for 'gpt-3.5-turbo' has been updated from 4000 to 4001.

### CODE REVIEW

**Comment by zmeir** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
interesting

My intuition was that the commit messages might direct the LLM to focus on the most important changes when choosing the title.

I will try tweaking the prompt a bit, to make it more conservative in using the commit messages

**Comment by mrT23** [comment]
image
with https://github.com/Codium-ai/pr-agent/pull/188

**Pull request closed without merging**
